<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>CombatLab.Cli</RootNamespace>
    <AssemblyName>CombatLab.Cli</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CombatLab.Runner\CombatLab.Runner.csproj" />
  </ItemGroup>
</Project>
