namespace Battle.Contracts.Events;

public enum CombatEventType
{
    BattleStarted,
    DecisionMade,
    ActionCommitted,
    ActionPhaseChanged,
    ActionCancelled,
    MoveStarted,
    PositionChanged,
    MoveEnded,
    AttackPrepared,
    ConflictResolved,
    AttackHit,
    AttackMissed,
    Blocked,
    Dodged,
    Countered,
    DamageApplied,
    ResourceChanged,
    EffectAdded,
    EffectRemoved,
    StateChanged,
    KnockbackApplied,
    WallImpact,
    GrabStarted,
    GrabEnded,
    FinisherTriggered,
    FighterDefeated,
    TimeoutReached,
    DrawDeclared,
    BattleEnded,
}
